### PR TITLE
WIP: Improve UI, some a11y

### PR DESCRIPTION
**Pull request by ssssoz**

### CODE REVIEW

**Comment by JosephMcArthur** [comment]
Shall we do fonts the same way we do them on the infrastructure site?

```
<!--
--
  | GET FONTS AND GET THEM FAST.
  | FROM: https://csswizardry.com/2020/05/the-fastest-google-fonts/
  | - 1. Preemptively warm up the fonts’ origin.
  | -
  | - 2. Initiate a high-priority, asynchronous fetch for the CSS file. Works in
  | -    most modern browsers.
  | -
  | - 3. Initiate a low-priority, asynchronous fetch that gets applied to the page
  | -    only after it’s arrived. Works in all browsers with JavaScript enabled.
  | -
  | - 4. In the unlikely event that a visitor has intentionally disabled
  | -    JavaScript, fall back to the original method. The good news is that,
  | -    although this is a render-blocking request, it can still make use of the
  | -    preconnect which makes it marginally faster than the default.
  | -->
  |  
  | <!-- [1] -->
  | <link rel="preconnect"
  | href="https://fonts.gstatic.com"
  | crossorigin />
  |  
  | <!-- [2] -->
  | <link rel="preload"
  | as="style"
  | href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Roboto+Mono:ital,wght@0,400;1,400&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" />
  | <!-- [3] -->
  | <link rel="stylesheet"
  | href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Roboto+Mono:ital,wght@0,400;1,400&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
  | media="print" onload="this.media='all'" />
  |  
  | <!-- [4] -->
  | <noscript>
  | <link rel="stylesheet"
  | href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Roboto+Mono:ital,wght@0,400;1,400&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" />
  | </noscript>
```

**Comment by ssssoz** [comment]
Hmm well currently, all additional JS + CSS are injected in the <head> via the Ghost UI (the CSS on this PR are redundant) -- do you think we should modify the templates or avoid doing that in case of a major update to our theme? (I think the latter might make sense, even if we did modify the templates slightly to remove the authors)

**Comment by JosephMcArthur** [comment]
Not sure. I defer to you on what makes sense, you know the code and are much more experienced than me.  

Here's some info you might need from me to make the call on what makes sense... 

It looks Casper is updated almost monthly with minor updates (https://github.com/TryGhost/Casper/releases?after=3.0.6) and the 2-->3 changed happened this time last year (so, not expecting it to happen soon). The most recent update was 2 days ago (sigh). So, I'm expecting we might need to make some minor updates each month (or, at least check in each month to see if an update is worth making).

If it took ~1 hour a month to keep this aligned and very performant (aka make updates we think are good) I'd be pretty happy (after, obviously this initial period of learning / investment and one or two minor updates where we may need to find a bit of a rhythm). Hell, if some of our updates are just 'good for all' maybe we could even submit a PR to them and see what happens?

**Comment by JosephMcArthur** [comment]
Couple of things.

Currently in `default.hbs` there is code to get the inter fonts. It's also in the code injection. Is that intended, seems to have in pages twice so I guess not.

Also, could we just include https://github.com/OAButton/ghost-blog-theme/pull/1#issuecomment-711173906 in that code injection? Since it's injected into the head it seems like it might have the same affect as putting it in the code directly. I hope so, as that's where analytics is 🙃

**Comment by JosephMcArthur** [comment]
FYI I have added some more custom CSS to adjust colors on the homepage / posts so they pass accessibility tests and don't affect styling too greatly (in my opinion). Can reverse if it looks bad, but I don't think it does.

**Comment by JosephMcArthur** [comment]
I've signed up here: https://gscan.ghost.org/?s=true. It may be worth you doing the same.

**Comment by ssssoz** [comment]
> FYI I have added some more custom CSS to adjust colors on the homepage / posts so they pass accessibility tests and don't affect styling too greatly (in my opinion). Can reverse if it looks bad, but I don't think it does.

No problem; wondering if you’re using the CSS variables?

Also, I’ve been doing the styling for dark mode, I’m assuming your computer is on light mode right?

**Comment by JosephMcArthur** [comment]
I did use the variable :)

It is in light mode, yes. I had a feeling dark mode may be an issue but figured it wouldn't for at least… a few hours ;)

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Custom stuff for dark mode is good now too!

**Comment by ssssoz** [comment]
Cleaned up the header injection & re-uploaded the compressed theme files with the faster font loading script.

**Comment by sssoz** [comment]
Cleaned up the header injection & re-uploaded the compressed theme files with the faster font loading script.

**Pull request merged**
